# https://aquasecurity.github.io/trivy/v0.29.2/docs/references/cli/image/
steps:
  - label: "Build Docker Image"
    command: "docker build -t bitcoin-core:$TAG ."
    plugins:
      - docker#v5.11.0:
          image: "docker"

  - label: "Scan Docker Image for Vulnerabilities"
    command: "trivy image --exit-code 1 --severity MEDIUM,HIGH,CRITICAL bitcoin-core:$TAG"
    plugins:
      - docker#v5.11.0:
          image: "aquasec/trivy"

  - label: "Push Docker Image to Registry"
    command: "docker push $REGISTRY_URL/bitcoin-core:$TAG"
    plugins:
      - docker#v5.11.0:
          image: "docker"

  - wait

  - label: "Deploy to Kubernetes"
    command: "./deploy-k8s.sh"
    env:
      KUBECONFIG: $KUBECONFIG_PATH

  - wait

  - label: "Verify Deployment"
    command: "kubectl rollout status deployment/bitcoin-core-deployment"
    env:
      KUBECONFIG: $KUBECONFIG_PATH