# https://kubernetes.io/docs/concepts/storage/persistent-volumes
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcoin-core-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    path: /tmp
    server: <SERVER>